name: iCore
version: '0.8.5'
main: net.curxxed.dev.icore.plugin.iCore
authors: [ curxxed ]
description: This plugin is an advanced Core plugin for Minecraft servers, providing a wide range of powerful commands and features for server management with a focus on performance and user experience and is very user-friendly.
